name       : kdepim-apps-libs
version    : 20.04.3
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kdepim-apps-libs-20.04.3.tar.xz : 7d69ac9cecfe0035e4806f0ff43fd41ac3755d788fffea9fd51427e1bc7027e3
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM mail related libraries
description: |
    KDE PIM mail related libraries
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-contacts-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - ki18n-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkleo-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
