name       : kdepim-apps-libs
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kdepim-apps-libs-17.08.1.tar.xz : 082e8059887dfeece38b30a4955319fa586045666c6c020dadeffba7e9aa0f00
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM mail related libraries
description: |
    KDE PIM mail related libraries
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - ki18n-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
