name       : kdepim-apps-libs
version    : 18.08.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kdepim-apps-libs-18.08.2.tar.xz : 10ac6453b8bd961c6ad0a2fde1e7f4893bec25fe13307f34bb1fb6d82ce8b15a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM mail related libraries
description: |
    KDE PIM mail related libraries
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - ki18n-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
