name       : kdepim-apps-libs
version    : 18.12.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kdepim-apps-libs-18.12.0.tar.xz : fd181d64229efc00633ad686616949670ba71555785314a897619b2580b1c3a3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM mail related libraries
description: |
    KDE PIM mail related libraries
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - ki18n-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
