name       : kdepim-apps-libs
version    : 19.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kdepim-apps-libs-19.08.1.tar.xz : 40a265cde8770a3fd6181b656da49d460dc67ed06d175067da0092116cd9862e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM mail related libraries
description: |
    KDE PIM mail related libraries
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - ki18n-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
